import { Report, Hospital, Volunteer, BlogPost, FAQ, DonationTier, Testimonial } from '@/types'

export const mockReports: Report[] = [
  {
    id: '1',
    title: 'Chó bị thương trên đường Nguyễn Huệ',
    description: 'Phát hiện một chú chó bị thương ở chân phải, đang nằm bên vệ đường. Cần hỗ trợ y tế gấp.',
    animalType: 'Chó',
    species: 'Chó ta',
    condition: 'INJURED',
    latitude: 10.7769,
    longitude: 106.7009,
    address: 'Đường Nguyễn Huệ, Quận 1, TP.HCM',
    images: [],
    status: 'PENDING',
    priority: 'HIGH',
    userId: 'user1',
    createdAt: '2026-05-30T10:00:00Z',
    updatedAt: '2026-05-30T10:00:00Z',
  },
  {
    id: '2',
    title: 'Mèo bị bỏ rơi tại công viên',
    description: 'Ba chú mèo con bị bỏ rơi trong hộp carton tại công viên Tao Đàn. Cần người nhận nuôi.',
    animalType: 'Mèo',
    species: 'Mèo ta',
    condition: 'ABANDONED',
    latitude: 10.7731,
    longitude: 106.6941,
    address: 'Công viên Tao Đàn, Quận 1, TP.HCM',
    images: [],
    status: 'ASSIGNED',
    priority: 'MEDIUM',
    userId: 'user2',
    createdAt: '2026-05-29T14:30:00Z',
    updatedAt: '2026-05-29T15:00:00Z',
  },
  {
    id: '3',
    title: 'Chim bồ câu bị gãy cánh',
    description: 'Phát hiện chim bồ câu bị gãy cánh trái, không thể bay được. Đang tạm giữ tại nhà.',
    animalType: 'Chim',
    species: 'Bồ câu',
    condition: 'INJURED',
    latitude: 10.7858,
    longitude: 106.6773,
    address: 'Đường Trần Hưng Đạo, Quận 5, TP.HCM',
    images: [],
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    userId: 'user3',
    createdAt: '2026-05-28T09:15:00Z',
    updatedAt: '2026-05-28T11:00:00Z',
  },
  {
    id: '4',
    title: 'Rùa biển mắc lưới trên bãi biển',
    description: 'Rùa biển con bị mắc lưới đánh cá trên bãi biển. Tình trạng nguy kịch cần cứu hộ ngay.',
    animalType: 'Rùa',
    species: 'Rùa biển xanh',
    condition: 'CRITICAL',
    latitude: 16.0544,
    longitude: 108.2022,
    address: 'Bãi biển Mỹ Khê, Đà Nẵng',
    images: [],
    status: 'PENDING',
    priority: 'CRITICAL',
    userId: 'user4',
    createdAt: '2026-05-31T07:00:00Z',
    updatedAt: '2026-05-31T07:00:00Z',
  },
  {
    id: '5',
    title: 'Khỉ bị thương trong khu dân cư',
    description: 'Một chú khỉ nhỏ bị thương, lạc vào khu dân cư. Nghi ngờ bị điện giật.',
    animalType: 'Khỉ',
    species: 'Khỉ đuôi dài',
    condition: 'CRITICAL',
    latitude: 10.8231,
    longitude: 106.6297,
    address: 'Quận 12, TP.HCM',
    images: [],
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    userId: 'user5',
    createdAt: '2026-05-31T08:30:00Z',
    updatedAt: '2026-05-31T09:00:00Z',
  },
  {
    id: '6',
    title: 'Chó hoang cần tiêm phòng',
    description: 'Nhóm chó hoang khoảng 5 con sinh sống tại khu vực và cần được tiêm phòng dại.',
    animalType: 'Chó',
    species: 'Chó ta',
    condition: 'SICK',
    latitude: 10.8020,
    longitude: 106.7147,
    address: 'Quận Bình Thạnh, TP.HCM',
    images: [],
    status: 'PENDING',
    priority: 'HIGH',
    userId: 'user6',
    createdAt: '2026-05-30T16:00:00Z',
    updatedAt: '2026-05-30T16:00:00Z',
  },
]

export const mockHospitals: Hospital[] = [
  {
    id: '1',
    name: 'Bệnh viện Thú y PetCare',
    email: 'contact@petcare.vn',
    phone: '028 3822 1234',
    website: 'https://petcare.vn',
    latitude: 10.7769,
    longitude: 106.7009,
    address: '123 Nguyễn Thị Minh Khai, Quận 1, TP.HCM',
    city: 'TP.HCM',
    description: 'Bệnh viện thú y hàng đầu với đội ngũ bác sĩ giàu kinh nghiệm. Chuyên khám chữa bệnh, phẫu thuật và chăm sóc sức khỏe toàn diện cho thú cưng.',
    logo: '',
    verified: true,
    operatingHours: '07:00 - 21:00',
    services: ['Khám tổng quát', 'Phẫu thuật', 'Tiêm phòng', 'Siêu âm', 'Xét nghiệm', 'Cấp cứu 24/7'],
    managerId: 'manager1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    distance: 1.2,
  },
  {
    id: '2',
    name: 'Phòng khám Thú y Sài Gòn',
    email: 'info@saigonvet.vn',
    phone: '028 3825 5678',
    latitude: 10.7858,
    longitude: 106.6773,
    address: '456 Trần Hưng Đạo, Quận 5, TP.HCM',
    city: 'TP.HCM',
    description: 'Phòng khám thú y uy tín với hơn 15 năm kinh nghiệm. Chuyên điều trị các bệnh nội khoa, ngoại khoa cho chó mèo.',
    logo: '',
    verified: true,
    operatingHours: '08:00 - 20:00',
    services: ['Khám tổng quát', 'Tiêm phòng', 'Triệt sản', 'Nha khoa', 'Xét nghiệm'],
    managerId: 'manager2',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
    distance: 2.5,
  },
  {
    id: '3',
    name: 'Animal Hospital Đà Nẵng',
    email: 'contact@animalhospital.dn',
    phone: '0236 3888 999',
    latitude: 16.0544,
    longitude: 108.2022,
    address: '789 Nguyễn Văn Linh, Hải Châu, Đà Nẵng',
    city: 'Đà Nẵng',
    description: 'Bệnh viện thú y hiện đại tại Đà Nẵng với trang thiết bị tiên tiến. Chuyên cứu hộ và điều trị động vật hoang dã.',
    logo: '',
    verified: true,
    operatingHours: '07:30 - 19:30',
    services: ['Cứu hộ động vật hoang dã', 'Phẫu thuật', 'Chẩn đoán hình ảnh', 'Xét nghiệm', 'Nội trú'],
    managerId: 'manager3',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
    distance: 5.0,
  },
  {
    id: '4',
    name: 'VetPlus Clinic',
    email: 'hello@vetplus.vn',
    phone: '028 3999 1111',
    latitude: 10.8020,
    longitude: 106.7147,
    address: '321 Điện Biên Phủ, Bình Thạnh, TP.HCM',
    city: 'TP.HCM',
    description: 'Phòng khám thú y cao cấp với dịch vụ chăm sóc toàn diện. Đội ngũ bác sĩ được đào tạo tại nước ngoài.',
    logo: '',
    verified: true,
    operatingHours: '08:00 - 22:00',
    services: ['Khám tổng quát', 'Phẫu thuật thẩm mỹ', 'Spa & Grooming', 'Tiêm phòng', 'Tư vấn dinh dưỡng'],
    managerId: 'manager4',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-02-15T00:00:00Z',
    distance: 3.1,
  },
  {
    id: '5',
    name: 'Wildlife Rescue Center Hà Nội',
    email: 'rescue@wildlife-hn.org',
    phone: '024 3777 2222',
    latitude: 21.0285,
    longitude: 105.8542,
    address: '100 Hoàng Quốc Việt, Cầu Giấy, Hà Nội',
    city: 'Hà Nội',
    description: 'Trung tâm cứu hộ động vật hoang dã lớn nhất miền Bắc. Chuyên cứu hộ, phục hồi và tái thả động vật hoang dã.',
    logo: '',
    verified: true,
    operatingHours: '06:00 - 22:00',
    services: ['Cứu hộ 24/7', 'Phục hồi chức năng', 'Tái thả tự nhiên', 'Nghiên cứu bảo tồn', 'Giáo dục cộng đồng'],
    managerId: 'manager5',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    distance: 10.0,
  },
  {
    id: '6',
    name: 'Happy Paws Veterinary',
    email: 'info@happypaws.vn',
    phone: '028 3666 3333',
    latitude: 10.7628,
    longitude: 106.6824,
    address: '55 Lý Tự Trọng, Quận 1, TP.HCM',
    city: 'TP.HCM',
    description: 'Phòng khám thú y thân thiện, chuyên chăm sóc sức khỏe cho thú cưng với giá cả phải chăng.',
    logo: '',
    verified: false,
    operatingHours: '09:00 - 18:00',
    services: ['Khám tổng quát', 'Tiêm phòng', 'Tắm & Cắt tỉa', 'Bán thuốc'],
    managerId: 'manager6',
    createdAt: '2026-03-15T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    distance: 1.8,
  },
]

export const mockVolunteers: Volunteer[] = [
  {
    id: '1',
    bio: 'Tình nguyện viên cứu hộ động vật với 5 năm kinh nghiệm. Đã tham gia hơn 100 vụ cứu hộ.',
    expertise: ['Cứu hộ chó mèo', 'Sơ cứu thú y', 'Vận chuyển động vật'],
    avatar: '',
    rating: 4.9,
    reviews: 127,
    verified: true,
    certifications: ['Chứng chỉ sơ cứu thú y', 'Chứng chỉ cứu hộ động vật'],
    userId: 'vol1',
    user: { id: 'vol1', email: 'minh@email.com', fullName: 'Nguyễn Văn Minh', role: 'VOLUNTEER', status: 'ACTIVE', createdAt: '', updatedAt: '' },
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    bio: 'Bác sĩ thú y tình nguyện. Chuyên khám chữa bệnh miễn phí cho động vật cơ nhỡ.',
    expertise: ['Khám chữa bệnh', 'Phẫu thuật', 'Tiêm phòng'],
    avatar: '',
    rating: 5.0,
    reviews: 89,
    verified: true,
    certifications: ['Bằng Bác sĩ Thú y', 'Chứng chỉ phẫu thuật'],
    userId: 'vol2',
    user: { id: 'vol2', email: 'lan@email.com', fullName: 'Trần Thị Lan', role: 'VOLUNTEER', status: 'ACTIVE', createdAt: '', updatedAt: '' },
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
  {
    id: '3',
    bio: 'Sinh viên ngành Thú y, đam mê bảo vệ động vật hoang dã. Hoạt động chủ yếu vào cuối tuần.',
    expertise: ['Chăm sóc động vật hoang dã', 'Giáo dục cộng đồng'],
    avatar: '',
    rating: 4.7,
    reviews: 45,
    verified: true,
    certifications: ['Chứng chỉ tình nguyện viên'],
    userId: 'vol3',
    user: { id: 'vol3', email: 'hung@email.com', fullName: 'Lê Đức Hùng', role: 'VOLUNTEER', status: 'ACTIVE', createdAt: '', updatedAt: '' },
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
]

export const mockBlogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Hướng dẫn sơ cứu động vật bị thương',
    excerpt: 'Khi phát hiện động vật bị thương, việc sơ cứu đúng cách có thể cứu sống chúng. Bài viết chia sẻ các bước sơ cứu cơ bản.',
    content: '',
    category: 'Hướng dẫn',
    author: 'BS. Trần Thị Lan',
    date: '2026-05-28',
    readTime: '5 phút',
    image: '',
    tags: ['sơ cứu', 'hướng dẫn', 'động vật bị thương'],
  },
  {
    id: '2',
    title: 'Câu chuyện cứu hộ: Rùa biển mắc lưới tại Đà Nẵng',
    excerpt: 'Chia sẻ về hành trình cứu hộ thành công một chú rùa biển xanh bị mắc lưới đánh cá trên bãi biển Mỹ Khê.',
    content: '',
    category: 'Câu chuyện',
    author: 'Nguyễn Văn Minh',
    date: '2026-05-25',
    readTime: '8 phút',
    image: '',
    tags: ['cứu hộ', 'rùa biển', 'Đà Nẵng'],
  },
  {
    id: '3',
    title: 'Tại sao bảo vệ động vật hoang dã quan trọng?',
    excerpt: 'Động vật hoang dã đóng vai trò quan trọng trong hệ sinh thái. Tìm hiểu vì sao chúng ta cần hành động ngay.',
    content: '',
    category: 'Kiến thức',
    author: 'TS. Phạm Văn An',
    date: '2026-05-20',
    readTime: '6 phút',
    image: '',
    tags: ['bảo tồn', 'động vật hoang dã', 'hệ sinh thái'],
  },
  {
    id: '4',
    title: 'Top 10 loài động vật cần được bảo vệ tại Việt Nam',
    excerpt: 'Danh sách 10 loài động vật đang bị đe dọa nghiêm trọng nhất tại Việt Nam và nỗ lực bảo tồn.',
    content: '',
    category: 'Kiến thức',
    author: 'Lê Đức Hùng',
    date: '2026-05-15',
    readTime: '10 phút',
    image: '',
    tags: ['bảo tồn', 'loài nguy cấp', 'Việt Nam'],
  },
  {
    id: '5',
    title: 'Cách nuôi dưỡng mèo hoang sau cứu hộ',
    excerpt: 'Bí quyết chăm sóc và thuần hóa mèo hoang sau khi được cứu hộ, giúp chúng thích nghi với môi trường mới.',
    content: '',
    category: 'Hướng dẫn',
    author: 'BS. Trần Thị Lan',
    date: '2026-05-10',
    readTime: '7 phút',
    image: '',
    tags: ['mèo hoang', 'chăm sóc', 'thuần hóa'],
  },
  {
    id: '6',
    title: 'Wild Rescue: Hành trình 1 năm và hơn 500 vụ cứu hộ',
    excerpt: 'Nhìn lại hành trình 1 năm hoạt động của Wild Rescue với những con số ấn tượng và câu chuyện cảm động.',
    content: '',
    category: 'Tin tức',
    author: 'Wild Rescue Team',
    date: '2026-05-05',
    readTime: '4 phút',
    image: '',
    tags: ['Wild Rescue', 'cột mốc', 'cộng đồng'],
  },
]

export const mockFAQs: FAQ[] = [
  {
    id: '1',
    question: 'Làm thế nào để báo cáo một động vật cần giúp đỡ?',
    answer: 'Bạn có thể báo cáo qua ứng dụng di động hoặc website bằng cách nhấn nút "Báo Cáo Cứu Hộ", điền thông tin về loại động vật, tình trạng, vị trí và đính kèm ảnh chụp. Hệ thống sẽ tự động chuyển thông tin đến đội cứu hộ gần nhất.',
    category: 'Sử dụng',
  },
  {
    id: '2',
    question: 'Tôi cần làm gì khi phát hiện động vật hoang dã bị thương?',
    answer: 'Đầu tiên, giữ khoảng cách an toàn và không cố bắt động vật. Chụp ảnh và ghi lại vị trí chính xác. Sau đó, báo cáo qua ứng dụng Wild Rescue hoặc gọi đường dây nóng 1900-WILD. Nếu tình trạng nguy kịch, hãy liên hệ trung tâm cứu hộ hoặc bệnh viện thú y gần nhất.',
    category: 'Cứu hộ',
  },
  {
    id: '3',
    question: 'Làm sao để đăng ký tình nguyện viên?',
    answer: 'Truy cập trang "Tình Nguyện Viên" trên website hoặc ứng dụng, điền form đăng ký với thông tin cá nhân, kỹ năng và vùng hoạt động. Sau khi xác minh, bạn sẽ nhận được thông báo về các vụ cứu hộ trong khu vực.',
    category: 'Tình nguyện',
  },
  {
    id: '4',
    question: 'Chi phí khám chữa cho động vật được tính như thế nào?',
    answer: 'Động vật hoang dã được cứu hộ sẽ được khám chữa miễn phí tại các bệnh viện đối tác. Chi phí được tài trợ từ quỹ quyên góp cộng đồng. Với thú cưng, chi phí sẽ tùy thuộc vào bệnh viện và dịch vụ.',
    category: 'Chi phí',
  },
  {
    id: '5',
    question: 'Wild Rescue hoạt động ở những khu vực nào?',
    answer: 'Hiện tại Wild Rescue đang hoạt động tại TP.HCM, Hà Nội, Đà Nẵng và đang mở rộng đến các tỉnh thành khác. Chúng tôi liên tục tìm kiếm đối tác bệnh viện và tình nguyện viên để mở rộng phạm vi hoạt động.',
    category: 'Chung',
  },
  {
    id: '6',
    question: 'Quyên góp của tôi được sử dụng như thế nào?',
    answer: '70% quỹ quyên góp được sử dụng trực tiếp cho công tác cứu hộ và điều trị. 20% dành cho hoạt động giáo dục cộng đồng và nâng cao nhận thức. 10% cho chi phí vận hành và phát triền nền tảng.',
    category: 'Quyên góp',
  },
  {
    id: '7',
    question: 'Tôi có thể nhận nuôi động vật đã được cứu hộ không?',
    answer: 'Có! Sau khi động vật được điều trị và phục hồi sức khỏe, chúng tôi tìm kiếm gia đình nhận nuôi phù hợp. Bạn cần đăng ký và trải qua quy trình xét duyệt để đảm bảo môi trường sống tốt nhất cho động vật.',
    category: 'Nhận nuôi',
  },
]

export const mockDonationTiers: DonationTier[] = [
  {
    id: '1',
    name: 'Người Bạn Nhỏ',
    amount: 50000,
    description: 'Đóng góp cho bữa ăn của một động vật',
    benefits: ['Nhận email cảm ơn', 'Cập nhật tình hình cứu hộ hàng tháng'],
  },
  {
    id: '2',
    name: 'Người Bảo Hộ',
    amount: 200000,
    description: 'Hỗ trợ chi phí khám chữa bệnh cơ bản',
    benefits: ['Tất cả quyền lợi gói Người Bạn Nhỏ', 'Nhận sticker Wild Rescue', 'Được ghi tên trên trang tri ân'],
    popular: true,
  },
  {
    id: '3',
    name: 'Anh Hùng Cứu Hộ',
    amount: 500000,
    description: 'Tài trợ ca phẫu thuật cho động vật',
    benefits: ['Tất cả quyền lợi gói Người Bảo Hộ', 'Nhận áo Wild Rescue', 'Được cập nhật riêng về ca cứu hộ', 'Mời tham dự sự kiện đặc biệt'],
  },
  {
    id: '4',
    name: 'Đại Sứ Bảo Tồn',
    amount: 2000000,
    description: 'Tài trợ toàn bộ quá trình cứu hộ & phục hồi',
    benefits: ['Tất cả quyền lợi gói Anh Hùng', 'Đặt tên cho động vật được cứu hộ', 'Tham quan trung tâm cứu hộ', 'Chứng nhận Đại Sứ Bảo Tồn', 'Video riêng về hành trình cứu hộ'],
  },
]

export const mockTestimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Phạm Thị Hoa',
    role: 'Người dùng',
    content: 'Nhờ Wild Rescue mà tôi đã cứu được một chú chó bị thương gần nhà. Đội ngũ phản hồi rất nhanh và chuyên nghiệp. Cảm ơn rất nhiều!',
    avatar: '',
    rating: 5,
  },
  {
    id: '2',
    name: 'BS. Nguyễn Minh Châu',
    role: 'Bệnh viện đối tác',
    content: 'Wild Rescue giúp kết nối bệnh viện với các ca cứu hộ một cách hiệu quả. Chúng tôi rất tự hào được là đối tác của nền tảng này.',
    avatar: '',
    rating: 5,
  },
  {
    id: '3',
    name: 'Trần Quốc Bảo',
    role: 'Tình nguyện viên',
    content: 'Làm tình nguyện viên cho Wild Rescue là trải nghiệm tuyệt vời. Mỗi lần cứu hộ thành công, tôi cảm thấy cuộc sống có ý nghĩa hơn rất nhiều.',
    avatar: '',
    rating: 5,
  },
]

export const stats = {
  animalsRescued: 1247,
  hospitals: 56,
  volunteers: 328,
  cities: 12,
}
